# Generated by Django 3.0.5 on 2020-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(default=0)),
                ('productsList', models.TextField(default='')),
                ('timeOfPurchase', models.CharField(default='', max_length=50)),
                ('grandTotal', models.IntegerField(default=0)),
            ],
        ),
    ]
