# Generated by Django 3.0.5 on 2020-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('code', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
