# Generated by Django 3.0.5 on 2020-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='', max_length=50)),
                ('productPrice', models.FloatField(default=0.0)),
                ('productTax', models.FloatField(default=0.0)),
                ('productCode', models.CharField(default='', max_length=15, unique=True)),
            ],
        ),
    ]
